apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: gslides
  namespace: default
spec:
  virtualHost:
    routes:
    - matcher:
        methods:
        - POST
        prefix: /submit/
      routeAction:
        single:
          destinationSpec:
            grpc:
              function: Submit
              package: api
              service: HubService
          upstream:
            name: CHANGEME
            namespace: default